
<head>
    <title>catalog</title>
    <style>
        body{
            background: white;
            font-family: 'Helvetica', 'Lucida Grande', 'Arial', sans-serif;
        }

        .form{
            height: 300px;
            width: 400px;
            margin: 160px auto;
        }

        form{
            border-radius: 5px;
            height: 100%;
            width: 100%;

            background: #777;
        }
        form label{
            display: inline-block;
            font-size: 13px;
            color: white;
        }
        input[type="checkbox"] {
            height: 15px;
            width: 15px;
        }
        form input{
            display: inline-block;
            margin: 5px 10px 10px 15px;
            width: 250px;
            background: #111;
            outline: 1px solid #333;
            border: 1px solid #000;
            padding: 5px;
            color: white;
            font-size: 12px;
        }
        .btn {
            display: inline-block;
            background: black;
            color: #fff;
            padding: 1rem 1.5rem;
            text-decoration: none;
            border-radius: 3px;
        }

        .bt{
            height: 150px;
            width: 200px;

        }

    </style>
</head>
<body>


<div class="bt">
    <a href="../index" class="btn">На главную</a> &nbsp;
</div>


<div class="form">

<form action="../Crud/createProduct" method="post" enctype="multipart/form-data" target="_blank">
    <br/>
    <input name="name" type="text" required/>
    <label for="name">Название</label><br/>

    <input name="description" type="text" required/>
    <label for="description">Описание</label><br/>

    <input name="text" type="text" required/>
    <label for="text">Полный текст</label><br/>

    <input type="file" name="img"/>
    <label for="img">Картинка</label><br/>

    <input name="category" type="text" required/>
    <label for="category">Категория</label><br/>

    <input type="checkbox" name="status" value=true>
    <label for="status">Скрывать\Показывать продукт</label><br/>

    <input type="submit" name="upload" value="Добавить продукт"/>

</form>
</div>

</body>
