
<head>
    <title>catalog</title>
    <style>
        body{
            background: white;
            font-family: 'Helvetica', 'Lucida Grande', 'Arial', sans-serif;
        }

        .btn {
            display: inline-block;
            background: black;
            color: #fff;
            padding: 1rem 1.5rem;
            text-decoration: none;
            border-radius: 3px;
        }

        .bt{
            height: 300px;
            width: 900px;
            margin: 200px auto;
        }

    </style>
</head>
<body>

<div class="bt">
<a href="./index/addProduct" class="btn">Добавить продукт</a> &nbsp;
<a href="./index/getProduct" class="btn">Посмотреть продукты</a> &nbsp;
<a href="./index/updateProduct" class="btn">Обновить продукт</a> &nbsp;
<a href="./index/delProduct" class="btn">Удалить продукт или категорию</a> &nbsp;
</div>

</body>
